### ISSUE TITLE
Tool causing site to 403

### ISSUE THREAD

**Issue by robteee** [PageModifiedOfficial/Check-My-Links#92]
Site works perfect but after running link checker links show 403 status. Clicking any link returns 403 and refreshing page does also. 
Links from Google also show 403.

Cleared cache and cookies.

Site is https://shop.advanceautoparts.com

https://www.screencast.com/t/8UPQ9cub

**Comment by revelt** [comment]
Yeah, I think it's some DoS prevention, site does load, https://tools.pingdom.com/#5aac3b43adc00000 it just bans you after "clicking" so many links in a succession..

I guess there's nothing we can do...

Let's close this ticket, it's outside of the scope. @robteee please confirm are you happy to close

**Comment by robteee** [comment]
Hi Revelt,

Thanks for your responses and insight. I'll close this.
