### ISSUE TITLE
Tons of 429 and 504 errors

### ISSUE THREAD

**Issue by robteee** [PageModifiedOfficial/Check-My-Links#94]
Hi,

Running the tool with both HEAD and GET produce significant false errors.

479 out of 556 (86%) are falsely being reported as "invalid".

https://www.screencast.com/t/C4Wma8wKc9

**Comment by robteee** [comment]
Is there some kind of logging I can provide to help diagnose why these status codes are being returned?

Thanks

**Comment by robteee** [comment]
I believe this is due to DDoS protection as other sites are blocking my IP for 15 minute intervals

**Comment by chasers** [comment]
Yeah we need rate limiting (#57) to prevent this.
