### ISSUE TITLE
**Feature Request** Check link HREF/Text to match <title>

### ISSUE THREAD

**Issue by nanobytz** [PageModifiedOfficial/Check-My-Links#95]
Is it possible to check the text in the anchor tag is found in linked page? i.e.
``<a href="Page1.html">Page1</a>``

Page1.html:
<title>All about Page1</title>

If there isn't a match have an option to issue a warning.
WARNING: URL may be referencing the wrong page.

This would be A HUGE benefit and would set you apart from other link checkers. I would pay for this feature.

**Comment by revelt** [comment]
Being precise, when we say "text in the anchor tag" do we mean any part of the URL?

For example,

`<a href="/shop/men/hats/search?color=black">Hats</a>`

should link to page where

`<title>Men Hats</title>`

?

Algorithmically, I imagine, get the title of the page landed, split by words, lowercase, perform a search for each word in the URL landed, if any matches Bob's your uncle.

The challenge is common words "and", "of" etc.

I can see how it could be checked, feature is not that difficult to implement just the config and making it "user friendly" is tedious.

**Comment by nanobytz** [comment]
Thanks for the reply!

Perhaps a color coded confidence score. Some kind of yellow to green linear
scale.

100% match = high confidence dark green background

50% match greenish yellow

0% no confidence yellow

As opposed to only reporting orange when there are no matches.

It’s good SEO / Design practice to make <title> and <h1> as appropriate to
the page as possible.

Manually checking pages all day is tedious. There's got to be a way to
automate monkey work.

Thanks for your help.

**Comment by chasers** [comment]
While this is a good idea, and I see the value ... I think it's out of scope for this project.
