### ISSUE TITLE
107 invalid links 500, while all headers are 200 ok

### ISSUE THREAD

**Issue by topacademictutors** [PageModifiedOfficial/Check-My-Links#98]
i have checked my website https://bit.ly/2Zf24uy internal links with chrome extension check my links but its showing all links as red invalid links (http 500 error). but when i visit my page its showing no error but when i click on 500 links which tool showing it show 500 page. please help me i am tired to use wordpress again and again i have fresh install wordpress and reenter data Manually. but still errors.
![AwesomeScreenshot-topacademictutors-co-uk--2019-08-17_4_46](https://user-images.githubusercontent.com/54210097/63211866-77829a80-c116-11e9-8698-f7d56c455117.png)

**Comment by chasers** [comment]
This is a rate limiting issue #57.
